---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-app
  labels:
    app: amazon-prime-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon-prime-app
  template:
    metadata:
      labels:
        app: amazon-prime-app
    spec:
      containers:
      - name: amazon-prime-container
        image: 294568841304.dkr.ecr.us-east-1.amazonaws.com/amazon-clone-k8s-eks-argocd:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
